// <auto-generated />
namespace ZaloCommunityDev.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addprofilea11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addprofilea11));
        
        string IMigrationMetadata.Id
        {
            get { return "201610301406212_add-profilea11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
